name: Code Quality

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Run Lint Check
      run: ./gradlew modernuix:lint

    - name: Run Detekt (Static Code Analysis)
      run: ./gradlew modernuix:detekt

    - name: Upload lint results
      uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: modernuix/build/reports/lint-results.html

    - name: Upload detekt results
      uses: actions/upload-artifact@v3
      with:
        name: detekt-results
        path: modernuix/build/reports/detekt
