name: Publish Package

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build library
      run: ./gradlew modernuix:assembleRelease

    - name: Publish to GitHub Packages
      run: ./gradlew modernuix:publish
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: modernuix
        path: modernuix/build/outputs/aar
